### ISSUE TITLE
Detect commits containing WIP

### ISSUE THREAD

**Issue by cmalard** [gr2m/wip-bot#10]
Hello there,

Would it be possible to detect if a commit contains the word WIP ?

Context : I use [OhMyZsh Git plugin](https://github.com/robbyrussell/oh-my-zsh/blob/accdcb2f1c3cca40527fef1fe4ab2d39eb6cf897/plugins/git/git.plugin.zsh#L241) wich easily create a commit named `--wip-- [skip ci]`

**Comment by gr2m** [comment]
yeah it would be, but it’s not yet implemented. Pull requests accepted :) 
You can deploy your own WIP bot instance easily using http://probot.glitch.me/ and then experiment with it

**Comment by Raul6469** [comment]
Hi! Would you be interested to receive a PR that implements that? It would check if the PR is still WIP based on the last commit name if I correctly understood

**Comment by gr2m** [comment]
Hey @Raul6469, it's all yours :) 

The idea is to load all commit messages from the pull request. If any of them starts with `WIP` then set the status to pending

**Comment by Raul6469** [comment]
Any of them? Once you have a commit containing `WIP`, how do you remove the wip status then?

**Comment by gr2m** [comment]
you clean up the commits locally and then `git push --force origin branch-of-pull-request` to update the commits in the pull request

I use semantic-release for all my projects, so the commit messages are significant as they determine new releases automatically. I try to keep the commits in master very clean. I either squash & merge the pull request or clean up the commits manually before merging

**Comment by gr2m** [comment]
done via https://github.com/gr2m/wip-bot/pull/32
