### ISSUE TITLE
Also block "Do not merge" PRs

### ISSUE THREAD

**Issue by fofr** [gr2m/wip-bot#26]
In my organisation (alphagov), we regularly mark PRs as "Do not merge" or "[DO NOT MERGE]". Does it make sense to add this to the wip-bot?

An example:
https://github.com/alphagov/government-frontend/pull/700

These are strings we often exclude:
https://github.com/binaryberry/seal/blob/435fe229733a4c0b872b6f309475451479dfcedd/config/alphagov.yml#L16-L21

I'm guessing it's just a case of updating this line:
https://github.com/gr2m/wip-bot/blob/master/lib/handle-pull-request-change.js#L5

**Comment by gr2m** [comment]
Hey Paul, thanks for opening the issue :)

How do you use "Do not merge"? Does it mean that the PR is still work in progress or are there other reasons why you would use that string?

**Comment by fofr** [comment]
@gr2m It can mean both, often it's because there's work in progress but sometimes because a PR on another repo is blocking the current one (ie WIP on another repo).

**Comment by gr2m** [comment]
okay, thanks. Would this change make it work for you?

```js
- const isWip = /\bwip\b/i.test(title)
+ const isWip = /\b(wip|do not merge)\b/i.test(title)
```

I am trying hard to keep the complexity very low as many folks including myself use the wip-bot as  a showcase & tempate for own probot apps.

I that change will do, I’d be happy to accept a pull request :)

**Comment by fofr** [comment]
@gr2m Yep, that's the exact change I was going to suggest. PR raised – #28.
