### ISSUE TITLE
WIP check is pending for PRs

### ISSUE THREAD

**Issue by dylanpinn** [gr2m/wip-bot#29]
Currently, when using your bot on one of our private repos the status is always pending and not failed.

![screenshot from 2018-01-23 11-45-32](https://user-images.githubusercontent.com/8828766/35252115-fe6d471c-0032-11e8-80fe-f121182fdd17.png)

**Comment by gr2m** [comment]
see #20, that is by design. 

When you think about it, it makes sense to set the status to "pending" instead of "error", doesn’t it? There is no error in the pull request per se, it’s just still being worked on, hence the pending status

**Comment by dylanpinn** [comment]
Ahhh, that makes total sense. Thanks for your help.
