### ISSUE TITLE
🐛🚫 Add tests

### ISSUE THREAD

**Issue by gr2m** [gr2m/wip-bot#33]
See https://probot.github.io/docs/testing/ and https://github.com/hoodiehq/first-timers-bot for reference.

**Comment by HeeL** [comment]
He he, honestly, I've came here to create the same issue, after following PR #32. I'm glad you came to the same conclusion. Actually, I've released my first bot today, you can have a look how I've tested it: https://github.com/HeeL/blogpost-checker
There are only unit tests, but I'm considering adding functional/integration tests in the future, to make sure probot works as expected.

**Comment by HeeL** [comment]
I can help as well

Am 14.02.2018 11:51 vorm. schrieb "Ayush Gupta" <notifications@github.com>:

**Comment by gr2m** [comment]
Maybe send both PRs and then review each other's work (I'll review, too)? That way we'll get the best of both :)

**Comment by rsarky** [comment]
Is this issue open to work on?

**Comment by gr2m** [comment]
@HeeL started a PR at https://github.com/gr2m/wip-bot/pull/37, maybe have a look at it to help review? I hope to do a review myself this weekend

**Comment by gr2m** [comment]
done via https://github.com/gr2m/wip-bot/pull/37
