### ISSUE TITLE
Destructure PR number for use

### ISSUE THREAD

**Issue by anshumanv** [gr2m/wip-bot#38]
Get number from - https://github.com/gr2m/wip-bot/blob/6d67f35f4168338a82b91885e16459e6aaf3df8c/lib/handle-pull-request-change.js#L4

Use in - 
https://github.com/gr2m/wip-bot/blob/6d67f35f4168338a82b91885e16459e6aaf3df8c/lib/handle-pull-request-change.js#L21

Lemme know if we need this @gr2m

**Comment by gr2m** [comment]
Yes, great catch, love when code becomes even simpler. A PR would be much appreciated :)
