### ISSUE TITLE
Support labels

### ISSUE THREAD

**Issue by jbrooksuk** [gr2m/wip-bot#57]
To keep PR titles cleaner, we use labels. Could we add configuration for this?

**Comment by gr2m** [comment]
Hi James, the WIP app is already looking at labels, see https://github.com/gr2m/wip-bot#usage. Does that work for you? I try to avoid configuration to keep the code base simple

**Comment by tamias** [comment]
FWIW, our organization uses the label "Work in Progress" rather than "wip".  It might be worth adding that to the regex in `containsWIP`.

**Comment by gr2m** [comment]
Yes, I’m a big fan of avoiding abbreviations where possible. Feel free to send a pull request for that
