### ISSUE TITLE
It got stuck

### ISSUE THREAD

**Issue by zeke** [gr2m/wip-bot#58]
This PR's title was changed, but the WIP check is still pending.

https://github.com/electron/simple-samples/pull/15

<img width="793" alt="screen shot 2018-03-16 at 9 15 39 pm" src="https://user-images.githubusercontent.com/2289/37551565-4fa342da-295f-11e8-952a-995d3405b647.png">

**Comment by codebytere** [comment]
I think this might be because my first commit contained `WIP` which looks like intended behavior per the `commitContainsWIP()` method...does this mean that it’s not possible to mark a PR as being ready unless i force push and rewrite history?

**Comment by gr2m** [comment]
> does this mean that it’s not possible to mark a PR as being ready unless i force push and rewrite history?

Yes. But you are not the first to be confused by it, I’m thinking to remove the parsing of commit messages altogether or to make it configurable.

By the way if something’s not working have a look at http://wip-bot.now.sh/_logs, the logs are public, it just doesn’t log for private repositories

**Comment by gr2m** [comment]
so yeah, https://github.com/electron/simple-samples/pull/15 is blocked because of the WIP commit

**Comment by zeke** [comment]
> I’m thinking to remove the parsing of commit messages altogether

I didn't realize it was parsing commit messages. I thought it was just based on PR title.

**Comment by gr2m** [comment]
Yeah I wish there was a way to communicate with users of an GitHub app ...
I documented the places it checks at https://github.com/gr2m/wip-bot#usage
