### ISSUE TITLE
don’t set status to success unless it has been set to error before

### ISSUE THREAD

**Issue by gr2m** [gr2m/wip-bot#6]
When creating a new pull request, the WIP bot sets a success status right away. I think it would be better if it would set no status at all, unless it has been set to error before

**Comment by rhwood** [comment]
I’d prefer to have it be marked as successful if never failing, since it’s not possible to merge from “mobile” devices like an iPad unless all checks are successful.

**Comment by gr2m** [comment]
but only if you enforce the status in the branch protection setting, right?

**Comment by rhwood** [comment]
No. GitHub in mobile refuses to merge even if statuses are not enforced.

**Comment by rhwood** [comment]
I should not that GitHub explicitly blocks the merge because it is being done from a mobile device, so this is deliberate on their part, and not a bug.

**Comment by gr2m** [comment]
I'll give this a try. Note that what I mean with this issue is that `WIP` would not even be listed in the checks, it would not be shown as pending or fail or success, it wouldn’t be shown at all, so I'm not sure how GitHub would even know to prevent the PR from merging

**Comment by rhwood** [comment]
I don’t know how GitHub handles a check that is not present, but I would have no objection to this if GitHub allowed the merge in mobile in that case.

**Comment by gr2m** [comment]
okay so what happens is this: if you require the status for WIP via the protected branch feature, then the WIP status will be shown as pending. And in this case you cannot merge the branch from mobile

![image](https://user-images.githubusercontent.com/39992/31312294-e73c0d76-ab73-11e7-9609-289a7369940c.png)

If you don’t enforce the status though it is possible

![image](https://user-images.githubusercontent.com/39992/31312301-019524f0-ab74-11e7-9d60-7f290ffbb9a5.png)

**Comment by gr2m** [comment]
I tested this and it’s not working. If the status is required via branch protection, not setting the status will prevent the PR from being merged. GItHub sets the status to pending right away
