### ISSUE TITLE
Add to GitHub Marketplace

### ISSUE THREAD

**Issue by maracuja-juice** [gr2m/wip-bot#62]
Have you thought about submitting your bot to the [GitHub Marketplace](https://developer.github.com/apps/marketplace/)?
Biggest Requirement for that is:
`GitHub Apps should have a minimum of 250 installations.` ([here](https://developer.github.com/apps/marketplace/creating-and-submitting-your-app-for-approval/requirements-for-listing-an-app-on-github-marketplace/) are the other requirements)

**Comment by gr2m** [comment]
Yeah I’ll do that, the requirements loosed up recently so it’s possible now. I’m just out vacationing for another week, but will look into it afterwards

**Comment by maracuja-juice** [comment]
Hey, cool! I just learned though that it isn't possible for completely free apps currently :/

**Comment by gr2m** [comment]
It’s happening: https://github.com/wip/app/pull/94 Follow updates at https://github.com/wip/app/issues/89
