### ISSUE TITLE
🎨🤖 Create a logo

### ISSUE THREAD

**Issue by gr2m** [gr2m/wip-bot#67]
The current avatar of the [WIP app](https://github.com/apps/wip) was meant as a placeholder. Now that it’s quite popular it would be nice if we could create a proper logo for it. 

I am not good at this :D But I thought maybe we could manage to make some kind of combination of a 
🤖 robot head and the letters WIP that create a face

![wip logo](https://user-images.githubusercontent.com/39992/39668305-dcd41256-507e-11e8-89a7-9395b2c92abb.png)

But hey I’m open to suggestions.

I’ll give full credit for the logo in the repository’s README and would also donate $50 in your honour to [Rails Girls Summer of Code](https://railsgirlssummerofcode.org/) or similar initiatives.

**Comment by micahilbery** [comment]
Thoughts?
![wip_bot](https://user-images.githubusercontent.com/10608836/39712067-4ee1921a-51e7-11e8-9839-db7133e97fc7.png)

**Comment by gr2m** [comment]
Cuuuute! Love how playful it is :) Thank you so much for putting it together Micah!

One challenge is to make it look great at 20x20 pixels. Sorry I should have mentioned it above. A bigger version with more details is still needed for the README, GitHub Apps page etc

Here is how the current logo would look like among the other status checks

<img width="400" alt="wip-preview" src="https://user-images.githubusercontent.com/39992/39716409-226f8bd0-51e5-11e8-97a8-d182852888c3.png">

Here are suggestions, but I trust your assessment very much, so please don’t take any of it as a must, these are just ideas from a non-designer

- remove the white space to fill out the whole image as m
- Increase the contrast
- Maybe add robot-ears? Sth [like this](https://www.flaticon.com/free-icon/robot_270137) maybe?
- Maybe make the head more like a rectangle
- Maybe make the head a little less high and more wide so there is more space for the letters?
- Maybe you could try to remove the move altogether to make it less high, similar to [this logo](https://iconscout.com/icon/robot-130)?

**Comment by gr2m** [comment]
Thanks @micahilbery, this looks great!

> not sure how the smaller one works on github

It’s being scaled down unfortunately, we cannot upload different versions for different resolutions.

The current image is 512x458 if I see it right, so there is some whitespace on top/bottom. I wonder if could use that to make the antenna taller as well as the letter W & P around it? I think they are currently quite hard to read on the scaled down version. 

Maybe we could try to fill out the letters instead of the outline?

**Comment by micahilbery** [comment]
![wip_bot_logo](https://user-images.githubusercontent.com/10608836/39767618-cacb6d7c-52ac-11e8-8208-a3c0e428d57b.png)
* Made the antenna slightly longer
* Tweaked the letters, removed outline, and made them bigger.
at 20px:
![20px](https://user-images.githubusercontent.com/10608836/39767761-1c017d80-52ad-11e8-9d35-ca63fb4a3c9e.png)

**Comment by gr2m** [comment]
Love it ❤️ 

Could you pleas send a pull request adding the logo to the assets folder, ideally in different formats? I’ll amend the PR to give you credit in the README :)

**Comment by micahilbery** [comment]
@gr2m For sure! What all would you like it as? I made it as an SVG and can easily export it to just about anything.

**Comment by gr2m** [comment]
I think an SVG and a PNG like the one above (without the whitespace on right and bottom if possible) would be great :) Thank you thank you thank you

**Comment by jbialy** [comment]
Great new logo! 🤖

**Comment by gr2m** [comment]
done via #69

**Comment by gr2m** [comment]
Hey @micahilbery, I had an idea and would love to hear what you think. 

The WIP app now looks the contruction emoji (:construction:) besides the term "WIP" in pull request titles. 

I wonder if we could maybe try to change the colors so it would somewhat match the colors from the construction emoji?

![image](https://user-images.githubusercontent.com/39992/48505664-71186880-e7fc-11e8-8482-ab3e884ddb6d.png)

Just a thought :)

**Comment by micahilbery** [comment]
@gr2m I have submitted a PR with the recolor. Unfortunately GitHub doesn't allow me to add images to comments anymore :man_shrugging: so I couldn't give a preview here.
