### ISSUE TITLE
Commit status isn't updated when pushing to existing Pull Request

### ISSUE THREAD

**Issue by jarrodldavis** [gr2m/wip-bot#8]
I've noticed that when an existing Pull Request is updated with new commits, this app doesn't set a commit status until the title is changed (or at least re-saved with the same text). For example, my initial commit [here](https://github.com/jarrodldavis/probot-gpg/pull/43) has a correctly-set status but the current head doesn't have any status from `wip-bot`.

**Comment by gr2m** [comment]
Thanks for reporting the issue! By the way the logs are public in case you run into any trouble. In your case some error occured: https://zeit.co/gr2m/wip-bot/ggkwiearje/logs?redirect=1&query=https%3A%2F%2Fgithub.com%2Fjarrodldavis%2Fprobot-gpg%2Fpull%2F43

I’ll investigate

**Comment by gr2m** [comment]
Ah I get what you mean now, it set the status, but it did not set it again after you pushed a commit

**Comment by cmalard** [comment]
Just ran into this, hope you can do it :beers:

**Comment by gr2m** [comment]
whee I just found out an easy fix for this, thanks to a tip @bkeepers, PR incoming 🎉

**Comment by gr2m** [comment]
this should no be resolved :)
