### ISSUE TITLE
Also set label when setting error status

### ISSUE THREAD

**Issue by rhwood** [gr2m/wip-bot#9]
I have a project that I would like to be able set/unset a label when a PR is a work in progress (as well as using the error/success status). Is that doable without requiring more extensive permissions for the WIP bot?

**Comment by gr2m** [comment]
That’s not possible I’m afraid, it would need to be implemented. It’s fairly simple to build you own GitHub app though and use `wip-bot` as a template. You can deploy it to Glitch and edit your code right there, just follow instructions at https://probot.glitch.me :)

Note that you can also search PRs based on their commit status, maybe that helps already?
https://help.github.com/articles/searching-issues-and-pull-requests/#search-based-on-commit-status

**Comment by rhwood** [comment]
I know a PR would need to be submitted. I was wondering if such a PR would, if accepted, require that every user of the bot reauthorize the bot?

**Comment by gr2m** [comment]
yes, people will get notifications about a change of permission and they woudl need to reauthorize the bot. But I would not accept such a PR at this point, I’m sorry. But happy to help you deploy your own bot instead :)
